### ISSUE TITLE
f1 score

### ISSUE THREAD

**Issue by edchengg** [scofield7419/XSRL-ACL#1]
Hi,
I am not sure if I understand the f1 measure for dependency SRL. 
How is this calculated? Do we care about the position of roles?
For example,
```
gold: ['_', 'A1', '_', '_', 'A2']
pred: ['_', '_', 'A1', '_', 'A2']
```
It seems from your code in eval.py line 25-34, you put A1 and A2 into a set and calculate the union with prediction (A1, A2). So in this case the F1 is 100?
Thank you!

**Comment by scofield7419** [comment]
@edchengg Hi there, sorry for the misunderstanding. Yes we should always consider the positions of arguments when measuring. In our latest practice we considered this point.
The thing is like we uploaded a very initial codes, where as you can find there are two evaluation tools `eval.py` and `eval_bio.py`, that can be confusing. 
We now have updated them with the authentic one.
Thanks.

**Comment by edchengg** [comment]
Thanks for your quick response! This makes sense.
BTW, do you use BIO format ? 
I got an F1 around 85 on the English test with mBERT. Do you think this is reasonable?
Thank you!

**Comment by scofield7419** [comment]
In our scenario, i.e., dependency SRL, one mention is with only one token. There is no need to concatenate an additional `BIO` tag to the role label.
For the English set (EWT), we got 80% F1 with only word form. With POS+dep-tree it reaches 87\%. Further with BERT, the final result goes to 90+\%.
But we did not try BERT representation only. I think your F1 score is valid tho.
