### ISSUE TITLE
copy of pre-processed data

### ISSUE THREAD

**Issue by edchengg** [scofield7419/XSRL-ACL#2]
Hi, I am trying to reproduce the results in Table 2 (SRC) but failed to get comparable results except for Finnish.

--|en | de | fr | es | pt | it | fi
--|-- | -- | -- | -- | -- | -- | --
reference |   | 43.2 | 53.1 | 41.2 | 44.2 | 44.4 | 31.6
mBERT - (Tagging) | 84.89 | 24.51 | 17.47 | 14.10 | 19.96 | 14.44 | 28.66

Do you mind provide a copy of pre-processed data? Thank you!

**Comment by scofield7419** [comment]
Hi there. 
My guess towards your lower scores is at the evaluation. Please see the `eval.py`.
To assess the performances, we have referenced the prior work which derived the concept of dependency SRL:
[unified-srl](https://github.com/bcmi220/unisrl/blob/master/srl_eval_utils.py), [sem-SRL](https://github.com/RuiCaiNLP/Semi_SRL/blob/master/nnet/run/srl/util.py).

Then you can reproduce the same results with ours (even above).
W.R.T the pre-processed data, we will release it once we return back to our lab.

**Comment by zhiweihu1103** [comment]
> Hi, I am trying to reproduce the results in Table 2 (SRC) but failed to get comparable results except for Finnish.
> 
> --	en	de	fr	es	pt	it	fi
> reference	 	43.2	53.1	41.2	44.2	44.4	31.6
> mBERT - (Tagging)	84.89	24.51	17.47	14.10	19.96	14.44	28.66
> Do you mind provide a copy of pre-processed data? Thank you!

when I run the trainPOS.py, I find in the eval.py, there not have EvalPRF class, look forward to your reply. However, I contact the authoe ,there is no reply. Do you mind to apply the DataUtils/eval.py file to me? Thanks.
![微信截图_20201008181026](https://user-images.githubusercontent.com/17820697/95445528-b6665600-0991-11eb-80b0-cffebc75b304.png)
